services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=3000
  #     - DATABASE_URL=postgresql://user:password@db:5432/allnewsdb
  #   depends_on:
  #     - db
  #   networks:
  #     - allnews-network
  #   ports:
  #     - "3000:3000"

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=allnewsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - allnews-network
    ports:
      - "5431:5432"

networks:
  allnews-network:
    driver: bridge

volumes:
  postgres-data: